id: I50441D8D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:48:08+00:00'
last_modified: '2022-06-08T04:51:55.992793+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16652
  title: གསུང་འབུམ། ཤཱཀྱ་མཆོག་ལྡན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4C9B:
      image_group_id: I4PD2600
      title: ''
      total_pages: 510
      order: 1
      base_file: 4C9B.txt
    '7476':
      image_group_id: I4PD2601
      title: ''
      total_pages: 536
      order: 2
      base_file: 7476.txt
    5CDD:
      image_group_id: I4PD2602
      title: ''
      total_pages: 442
      order: 3
      base_file: 5CDD.txt
    EF6D:
      image_group_id: I4PD2603
      title: ''
      total_pages: 480
      order: 4
      base_file: EF6D.txt
    C4FF:
      image_group_id: I4PD2604
      title: ''
      total_pages: 370
      order: 5
      base_file: C4FF.txt
    DBF8:
      image_group_id: I4PD2605
      title: ''
      total_pages: 532
      order: 6
      base_file: DBF8.txt
    BD4A:
      image_group_id: I4PD2606
      title: ''
      total_pages: 472
      order: 7
      base_file: BD4A.txt
    '1731':
      image_group_id: I4PD2607
      title: ''
      total_pages: 434
      order: 8
      base_file: 1731.txt
    F692:
      image_group_id: I4PD2608
      title: ''
      total_pages: 574
      order: 9
      base_file: F692.txt
    '1441':
      image_group_id: I4PD2609
      title: ''
      total_pages: 468
      order: 10
      base_file: 1441.txt
    D675:
      image_group_id: I4PD2610
      title: ''
      total_pages: 438
      order: 11
      base_file: D675.txt
    84AE:
      image_group_id: I4PD2611
      title: ''
      total_pages: 478
      order: 12
      base_file: 84AE.txt
    A19A:
      image_group_id: I4PD2612
      title: ''
      total_pages: 534
      order: 13
      base_file: A19A.txt
    AF99:
      image_group_id: I4PD2613
      title: ''
      total_pages: 536
      order: 14
      base_file: AF99.txt
    31EC:
      image_group_id: I4PD2614
      title: ''
      total_pages: 564
      order: 15
      base_file: 31EC.txt
    3A88:
      image_group_id: I4PD2615
      title: ''
      total_pages: 488
      order: 16
      base_file: 3A88.txt
    77E4:
      image_group_id: I4PD2616
      title: ''
      total_pages: 478
      order: 17
      base_file: 77E4.txt
    0AC9:
      image_group_id: I4PD2617
      title: ''
      total_pages: 542
      order: 18
      base_file: 0AC9.txt
    '4540':
      image_group_id: I4PD2618
      title: ''
      total_pages: 642
      order: 19
      base_file: 4540.txt
    F024:
      image_group_id: I4PD2619
      title: ''
      total_pages: 470
      order: 20
      base_file: F024.txt
    BC79:
      image_group_id: I4PD2620
      title: ''
      total_pages: 290
      order: 21
      base_file: BC79.txt
    49CD:
      image_group_id: I4PD2621
      title: ''
      total_pages: 454
      order: 22
      base_file: 49CD.txt
    4E2C:
      image_group_id: I4PD2622
      title: ''
      total_pages: 430
      order: 23
      base_file: 4E2C.txt
    4CAE:
      image_group_id: I4PD2623
      title: ''
      total_pages: 272
      order: 24
      base_file: 4CAE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
