id: P005552
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16652
  title: གསུང་འབུམ། ཤཱཀྱ་མཆོག་ལྡན།
  author: ''
  volumes:
    e1796a44b69b4d7589827ccdfa2537ad:
      image_group_id: I4PD2600
      title: ''
      volume_number: 1
      total_pages: 510
    5cf9e20d15ea44c6bafd1153595db5af:
      image_group_id: I4PD2601
      title: ''
      volume_number: 2
      total_pages: 536
    380c131d2893448393bf8da0d4be932c:
      image_group_id: I4PD2602
      title: ''
      volume_number: 3
      total_pages: 442
    fb4289ad680947b292ddb1982b0bd140:
      image_group_id: I4PD2603
      title: ''
      volume_number: 4
      total_pages: 480
    d4f107be99ab4041911b5feccc1a3f0e:
      image_group_id: I4PD2604
      title: ''
      volume_number: 5
      total_pages: 370
    0d4ea28dd424491ea14f05ea5643d775:
      image_group_id: I4PD2605
      title: ''
      volume_number: 6
      total_pages: 532
    60c6c8b98d8b43afbc9ef96e3e37010f:
      image_group_id: I4PD2606
      title: ''
      volume_number: 7
      total_pages: 472
    edd72fc822fc40939ce310648eb43b58:
      image_group_id: I4PD2607
      title: ''
      volume_number: 8
      total_pages: 434
    9538253e1d7e4c2d977d47a8bfc059f1:
      image_group_id: I4PD2608
      title: ''
      volume_number: 9
      total_pages: 574
    28b45897f19346368756cdb6bf35de1c:
      image_group_id: I4PD2609
      title: ''
      volume_number: 10
      total_pages: 468
    7f153a482a5a4dae9a9ecb4ff0ea1bbf:
      image_group_id: I4PD2610
      title: ''
      volume_number: 11
      total_pages: 438
    0b3cb0a12e9749e9ba0920f1989e6aa5:
      image_group_id: I4PD2611
      title: ''
      volume_number: 12
      total_pages: 478
    84fc0c519d0849c1820ba1d586743931:
      image_group_id: I4PD2612
      title: ''
      volume_number: 13
      total_pages: 534
    e96b7a5dee6d4242a75fcacb55817201:
      image_group_id: I4PD2613
      title: ''
      volume_number: 14
      total_pages: 536
    9f30b6aeb4bc4591a4ca06532ae7fd43:
      image_group_id: I4PD2614
      title: ''
      volume_number: 15
      total_pages: 564
    f335e800c4ea45d6813d6d5c20cf9540:
      image_group_id: I4PD2615
      title: ''
      volume_number: 16
      total_pages: 488
    61e2290d4cf346d8b75a28c546543e94:
      image_group_id: I4PD2616
      title: ''
      volume_number: 17
      total_pages: 478
    f6d5aa93c4174e98807c98f5aa8cab4f:
      image_group_id: I4PD2617
      title: ''
      volume_number: 18
      total_pages: 542
    cb12742e69604dedacdef78eaa266284:
      image_group_id: I4PD2618
      title: ''
      volume_number: 19
      total_pages: 642
    6029bf80860641e6975e7a9717c8cc8b:
      image_group_id: I4PD2619
      title: ''
      volume_number: 20
      total_pages: 470
    c31c1dcbe21644a68e108ebd22812819:
      image_group_id: I4PD2620
      title: ''
      volume_number: 21
      total_pages: 290
    3629c19b2fd748e69f93bb5558fda364:
      image_group_id: I4PD2621
      title: ''
      volume_number: 22
      total_pages: 454
    e1596af881844f32b305b2c97bb736a1:
      image_group_id: I4PD2622
      title: ''
      volume_number: 23
      total_pages: 430
    99e897c392c44e8e8a3c2773fe4f4e76:
      image_group_id: I4PD2623
      title: ''
      volume_number: 24
      total_pages: 272
